version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-exremely-strong-root-password
      MYSQL_DATABASE: music
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  nodejs:
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: music
    depends_on:
      - mysql
    command: sh -c './wait-for mysql:3306 -- npm start'
